"""0003 add biomarker_readings

Revision ID: 063e8d2d3c4a
Revises: 86448018a6cc
Create Date: 2026-04-19 19:46:24.572187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (referenced by JSONB variants)
import sqlmodel  # noqa: F401 (AutoString type lives here)


# revision identifiers, used by Alembic.
revision: str = '063e8d2d3c4a'
down_revision: Union[str, None] = '86448018a6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomarker_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('biomarker_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reference_min', sa.Float(), nullable=True),
    sa.Column('reference_max', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('lab_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomarker_readings_test_date'), 'biomarker_readings', ['test_date'], unique=False)
    op.create_index(op.f('ix_biomarker_readings_user_id'), 'biomarker_readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biomarker_readings_user_id'), table_name='biomarker_readings')
    op.drop_index(op.f('ix_biomarker_readings_test_date'), table_name='biomarker_readings')
    op.drop_table('biomarker_readings')
    # ### end Alembic commands ###
