"""0001 initial schema: users + workouts + recovery + periodization

Revision ID: 671d84dd7e24
Revises: 
Create Date: 2026-04-19 19:21:58.426351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
import sqlmodel  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '671d84dd7e24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('fitness_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('goals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('macrocycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('methodology', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('block_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macrocycles_user_id'), 'macrocycles', ['user_id'], unique=False)
    op.create_table('recovery_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('hrv_ms', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('muscle_soreness', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_recovery_user_date')
    )
    op.create_index(op.f('ix_recovery_metrics_date'), 'recovery_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_recovery_metrics_user_id'), 'recovery_metrics', ['user_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('methodology', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('difficulty_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workout_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('movements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('target_stimulus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rep_scheme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('equipment_required', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microcycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('macrocycle_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('week_index_in_macro', sa.Integer(), nullable=False),
    sa.Column('intensity_target', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('volume_target', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['macrocycle_id'], ['macrocycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('macrocycle_id', 'week_index_in_macro', name='uq_micro_macro_week')
    )
    op.create_index('idx_micro_user_date', 'microcycles', ['user_id', 'start_date'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('microcycle_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('order_in_day', sa.Integer(), nullable=False),
    sa.Column('shift', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('workout_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('focus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('generated_template_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['microcycle_id'], ['microcycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microcycle_id', 'date', 'order_in_day', name='uq_planned_micro_date_order')
    )
    op.create_index('idx_planned_user_date', 'planned_sessions', ['user_id', 'date'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('planned_session_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('workout_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rpe_score', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index('idx_planned_user_date', table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index('idx_micro_user_date', table_name='microcycles')
    op.drop_table('microcycles')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_recovery_metrics_user_id'), table_name='recovery_metrics')
    op.drop_index(op.f('ix_recovery_metrics_date'), table_name='recovery_metrics')
    op.drop_table('recovery_metrics')
    op.drop_index(op.f('ix_macrocycles_user_id'), table_name='macrocycles')
    op.drop_table('macrocycles')
    op.drop_table('users')
    # ### end Alembic commands ###
