"""0002 add personal_records

Revision ID: 86448018a6cc
Revises: 671d84dd7e24
Create Date: 2026-04-19 19:43:59.394920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (referenced by JSONB variants)
import sqlmodel  # noqa: F401 (AutoString type lives here)


# revision identifiers, used by Alembic.
revision: str = '86448018a6cc'
down_revision: Union[str, None] = '671d84dd7e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('record_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movement_name', 'record_type', name='uq_pr_user_movement_record')
    )
    op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_table('personal_records')
    # ### end Alembic commands ###
