"""0005 add weekly_reviews + session_feedback

Revision ID: ccb8fd52d5a9
Revises: 4a488a453e78
Create Date: 2026-04-19 19:51:02.562240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (referenced by JSONB variants)
import sqlmodel  # noqa: F401 (AutoString type lives here)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccb8fd52d5a9'
down_revision: Union[str, None] = '4a488a453e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planned_sessions', sa.Integer(), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('adherence_rate', sa.Float(), nullable=False),
    sa.Column('avg_rpe', sa.Float(), nullable=False),
    sa.Column('avg_readiness', sa.Float(), nullable=False),
    sa.Column('overall_satisfaction', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('weaknesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('recovery_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('volume_assessment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('progressions_detected', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('next_week_adjustments', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('coach_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ai_model_used', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reviews_created_at'), 'weekly_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_weekly_reviews_user_id'), 'weekly_reviews', ['user_id'], unique=False)
    op.create_table('session_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rpe_score', sa.Integer(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('technique_quality', sa.Integer(), nullable=False),
    sa.Column('pacing', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('energy_level_pre', sa.Integer(), nullable=False),
    sa.Column('energy_level_post', sa.Integer(), nullable=False),
    sa.Column('would_repeat', sa.Boolean(), nullable=False),
    sa.Column('favorite_part', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('least_favorite_part', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('movements_feedback', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_feedback_date'), 'session_feedback', ['date'], unique=False)
    op.create_index(op.f('ix_session_feedback_session_id'), 'session_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_feedback_user_id'), 'session_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_feedback_user_id'), table_name='session_feedback')
    op.drop_index(op.f('ix_session_feedback_session_id'), table_name='session_feedback')
    op.drop_index(op.f('ix_session_feedback_date'), table_name='session_feedback')
    op.drop_table('session_feedback')
    op.drop_index(op.f('ix_weekly_reviews_user_id'), table_name='weekly_reviews')
    op.drop_index(op.f('ix_weekly_reviews_created_at'), table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    # ### end Alembic commands ###
